/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author mathe
 */
public class JPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFramePrincipal
     */
    public JPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        //JPrincipal tela = new JPrincipal();
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JPrincipal().setVisible(true);

            }
        });*/
        JPrincipal tela = new JPrincipal();
        tela.setVisible(true);
        tela.Voltar();
        //tela.GerenciarValores();

    }

    public void Voltar(){
        JPanelPrincipal p = new JPanelPrincipal(this);
        setContentPane(p);
        pack();
    }

    public void GerenciarQuarto(){
        JPanelGerenciarQuarto p = new JPanelGerenciarQuarto(this);
        setContentPane(p);
        pack();
    }

    public void GerenciarReserva(){
        JPanelGerenciarReserva p = new JPanelGerenciarReserva(this);
        setContentPane(p);
        pack();
    }

    public void FazerCheckin(){
        JPanelCheckin p = new JPanelCheckin(this);
        setContentPane(p);
        pack();
    }

    public void GerenciarValores(){
        JPanelGerenciarValores p = new JPanelGerenciarValores(this);
        setContentPane(p);
        pack();
    }

    public void RealizarReserva(boolean editing, Long idQuarto){
        JPanelReservar panelReservar = new JPanelReservar(this);
        if(editing)panelReservar.setEditing(idQuarto);
        setContentPane(panelReservar);
        pack();
        setVisible(true);
    }

    public void Relatorio(){
        JPanelRelatorio panelRelatorio = new JPanelRelatorio(this);
        setContentPane(panelRelatorio);
        pack();
        setVisible(true);
    }

    public void EditarQuarto(boolean editing, int idQuarto){
        JPanelQuarto panelQuarto = new JPanelQuarto(this);
        if(editing) panelQuarto.setEditing(idQuarto);
        setContentPane(panelQuarto);
        pack();
        setVisible(true);
    }

    public void Valores(){
        JPanelGerenciarValores panelGerenciarValores = new JPanelGerenciarValores(this);
        setContentPane(panelGerenciarValores);
        pack();
        setVisible(true);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
